services:
  postgres:
    image: postgres:17-alpine3.21
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PUBLIC_PORT:-5434}:5432"
    command: [
      "postgres",
      "-c", "shared_preload_libraries=pg_stat_statements",
      "-c", "pg_stat_statements.track=all",
      "-c", "pg_stat_statements.max=10000",
      "-c", "log_connections=on"
    ]
    environment:
      POSTGRES_DB: "$DB_DATABASE"
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    volumes:
      - "${DB_DATA_PATH:-pg_data}":/var/lib/postgresql/data
